module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        bg:        'var(--bg)',
        card:      'var(--card)',
        surface:   'var(--surface)',
        surface2:  'var(--surface-2)',
        border:    'var(--border)',
        border2:   'var(--border-2)',
        ink:       'var(--ink)',
        ink2:      'var(--ink-2)',
        muted:     'var(--muted)',
        dim:       'var(--dim)',
        accent:    'var(--accent)',
        'canvas-bg': 'var(--canvas-bg)',
        'node-bg':     'var(--node-bg)',
        'node-header': 'var(--node-header-bg)',
        'node-border': 'var(--node-border)',
        'node-ink':    'var(--node-ink)',
        'node-muted':  'var(--node-muted)',
        'node-input':  'var(--node-input-bg)',
        'node-input-border': 'var(--node-input-border)',
        'ctrl-bg':     'var(--ctrl-bg)',
        'ctrl-border': 'var(--ctrl-border)',
        'ctrl-ink':    'var(--ctrl-ink)',
        'ctrl-muted':  'var(--ctrl-muted)',
        'ctrl-hover':  'var(--ctrl-hover)',
        'modal-bg':          'var(--modal-bg)',
        'modal-border':      'var(--modal-border)',
        'modal-ink':         'var(--modal-ink)',
        'modal-muted':       'var(--modal-muted)',
        'modal-stat-bg':     'var(--modal-stat-bg)',
        'modal-stat-border': 'var(--modal-stat-border)',
      },
      fontFamily: {
        sans:  ['Inter Tight', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['Newsreader', 'Georgia', 'serif'],
        mono:  ['JetBrains Mono', 'Cascadia Code', 'Menlo', 'monospace'],
      },
      borderRadius: {
        node: '5px',
      },
    },
  },
  plugins: [],
};
